### ISSUE TITLE
Jagged edges

### ISSUE THREAD

**Issue by rstacruz** [jorenvanhee/sass-burger#10]
If you notice, the in-between states seem to feature some antialiasing problems: (Firefox/OSX)

![pasted_image_5_15_15__4_03_am](https://cloud.githubusercontent.com/assets/74385/7640699/680d182a-fab7-11e4-924f-d30d7f895e2d.png)

Using translate3d may leave you with less aliased artifacts. This means using `translate3d(0,8px,0)` instead of `translateY(8px)`, and adding `translate3d(0,0,0)` to the burger state.

Also, perhaps it'd be nice to make it double the size then do `scale(0.5)` — this may help lessen the aliasing artifacts as well.

**Comment by rstacruz** [comment]
hm, nevermind — can confirm none of those hypotheses work on reducing aliasing on firefox, bummer.

**Comment by jorenvanhee** [comment]
Didn't notice this before, thanks for pointing it out.
I did some googling and found this: http://stackoverflow.com/questions/9235342/3d-css-transform-jagged-edges-in-firefox

`outline: 1px solid transparent;` on the different lines seems to fix it. I'll double check tomorrow.
