### ISSUE TITLE
Libsass compatibility

### ISSUE THREAD

**Issue by evertalbers** [jorenvanhee/sass-burger#16]
I tried your code on a grunt/libass/Foundation environment and I got an error. 

If I understood the notifications and what I Googled allright, the use of the deprecated "!global" seems to be problem, is there a way around this that you are aware of?

Other than this, Sass-burger is a beautiful piece of work!

**Comment by jorenvanhee** [comment]
Hi, which version of Libsass are you using?
It seems to work on http://sassmeister.com/.

**Comment by evertalbers** [comment]
Disclaimer: I don't exactly know what I'm doing, but I'll give you what I know:
I use the libsass version of Foundation, as described on http://foundation.zurb.com/docs/sass.html (under "Creating a Libsass project"). 

This is what I can see about versions: 
``
node-sass@0.9.6 node_modules/node-sass
├── node-watch@0.3.4
├── object-assign@1.0.0
├── get-stdin@3.0.2
├── node-sass-middleware@0.3.1
├── nan@1.3.0
├── shelljs@0.3.0
├── yargs@1.3.3
├── chalk@0.5.1 (ansi-styles@1.1.0, supports-color@0.2.0, escape-string-regexp@1.0.3, strip-ansi@0.3.0, has-ansi@0.1.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── mocha@1.21.5 (diff@1.0.8, growl@1.8.1, commander@2.3.0, escape-string-regexp@1.0.2, mkdirp@0.5.0, glob@3.2.3, jade@0.26.3, debug@2.0.0)
└── sinon@1.10.3 (util@0.10.3, formatio@1.0.2)
``
And this is the error notification: 
``
Running "sass:dist" (sass) task
Warning: /(path):(line number): error: error reading values after $height
 Use --force to continue.
``
Hope this helps.

**Comment by jorenvanhee** [comment]
Sorry for the late reaction, I'm on holiday right now. I'm going to look into this further, but for now, maybe issue #3 can help. Also thanks for the details with the versions.

**Comment by jorenvanhee** [comment]
Try updating grunt-sass to version 1.0.0 (zurb/foundation-libsass-template#23)

**Comment by andreasisaak** [comment]
I'm using grunt-sass 1.1.0. The bug with !global is unfortunately not resolved :)

**Comment by jorenvanhee** [comment]
Hmm, could you send me your grunt file?

**Comment by andreasisaak** [comment]
Do you need the complete gruntfile.js or only the package.json?

**Comment by jorenvanhee** [comment]
Could you give me both? And maybe also the sass code where you use the mixin. I just tried it with grunt-sass 1.1.0 and everything works in my case.

**Comment by jorenvanhee** [comment]
I'll close this issue for now.
