### ISSUE TITLE
Can you toggle the animation form 2 seperate buttons?

### ISSUE THREAD

**Issue by jinch** [jorenvanhee/sass-burger#19]
I am using the latest Foundation 6 release with the built in ".close-button" as well as the ".burger-icon" to toggle my menu. Is there a way to trigger the X off and on with a separate buttons? I tried to adjust the javascript to include a listen event for the ".close-button" but it didn't seam to work.

**Comment by jinch** [comment]
scratch.. this worked for me if anyone else has simulare issue.

$('#offCanvasLeft button.close-button').on('click', function() {
  $('#menuButton').removeClass('is-active');
});

**Comment by jorenvanhee** [comment]
Glad you figured it out :)
