### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mononelo** [jorenvanhee/sass-burger#20]
I'm not an expert user of compass and I became mad looking the way to import correctly this exension and I finally discovered that I have to do a **@import "burger";** in my scss. Please complete the documentation by adding this data to avoid other users to waste time.

_...and congratulations for this extension!_

Thanks!

**Comment by assumptionsoup** [comment]
And for those on webpack, it seems to be:
```
@import "~sass-burger/burger";
```

This is probably basic webpack knowledge, but as I'm learning, it took awhile to find.

**Comment by jorenvanhee** [comment]
Thanks for the heads up, I'm happy to accept a PR. For now people can find it here.
