### ISSUE TITLE
Unbound variable $burger-gutter

### ISSUE THREAD

**Issue by ilanbiala** [jorenvanhee/sass-burger#3]
When I import the scss and include the mixin, I get an `Unbound variable $burger-gutter` error.

**Comment by jorenvanhee** [comment]
Hi. I guess you're using an older version of Sass or libsass? (they unfortunately do not support !global)

You can change the top of the _burger.scss file to this as a workaround.
```sass
$burger-height: 0 !default;
$burger-gutter: 0 !default;

@mixin burger(...) {
    $burger-height: $height;
    $burger-gutter: $gutter;
```

I will get rid of the `!global` flag in the future. But for now, this should do the job.
Let me know if this worked for you.

**Comment by ilanbiala** [comment]
I'm using gulp-sass 1.3.3, which uses node-sass ^2.0.1.

**Comment by jorenvanhee** [comment]
And node-sass uses libsass :)
Did the workaround work for you?

**Comment by ilanbiala** [comment]
I haven't tried it yet, it seems to be supported in Libsass 3.1.0 which will be released soon and hopefully upstreamed ASAP.

**Comment by alfredbez** [comment]
I had the same issue and the workaround worked for me.

**Comment by jorenvanhee** [comment]
Thanks for letting me know. I will close this one.
Also, I'm working on v2 with more animations, and without this issue.
