### ISSUE TITLE
Comments using `//`

### ISSUE THREAD

**Issue by di5abled** [jorenvanhee/sass-burger#7]
Hy,

very nice mixin, only one thing I would change :)

Could you make your comments using `//` that they don't end up in the generated CSS?

If you mind I could also make a PR for that?

**Comment by jorenvanhee** [comment]
Good idea, I just read the [Sass Guidelines (section: writing comments)](http://sass-guidelin.es/#writing-comments) and they recommend this as well.
A PR would be great!
